---
- name: Docker | Disable SWAP memory
  ansible.builtin.shell: |
    swapoff --all
  tags: docker

- name: Docker | Disable SWAP in fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  tags: docker

- name: Docker | Install a list of packages
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
  tags: docker

- name: Docker | Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present
  tags: docker

- name: Docker | Add Docker stable repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_facts.lsb.codename }} stable
    filename: docker
    state: present
  tags: docker

- name: Docker | Install Docker Engine
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  tags: docker

- name: Docker | Add {{ vagrant_user }} user on docker group
  ansible.builtin.user:
    name: "{{ vagrant_user }}"
    groups: docker
    append: yes
  tags: docker

- name: Docker | Template a file to /etc/docker/daemon.json
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0640
  notify: Restart docker daemon
  tags: docker
