---
- name: Docker Compose | Install Docker Compose v{{ docker_compose_version }}
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    force: yes
    validate_certs: yes
    mode: 0755
  tags: docker_compose

- name: Docker Compose | Install command-line completion
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/docker/compose/{{ docker_compose_version }}/contrib/completion/bash/docker-compose"
    dest: /etc/bash_completion.d/docker-compose
    force: yes
    validate_certs: yes
    mode: 0644
  tags: docker_compose
